 version: '3.7'

 services:
   web:
     build: ./app
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - ./app/:/user/src/app/
     ports:
       - 8000:8000
     env_file:
       - ./.env.dev
     depends_on:
       - db
   db:
     image: postgres:12.0-alpine
     volumes:
       - postgres_data:/var/lib/postgresql/data/
     environment:
       - POSTGRES_USER=demo_docker_django
       - POSTGRES_PASSWORD=demo_docker_django
       - POSTGRES_DB=demo_docker_django_dev
 
 volumes:
   postgres_data:     
